[package]
name = "hygiea-component-redis-fred"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Redis (fred) component for hygiea"

[features]
distributed-lock = ["hygiea-core/distributed-lock"]

[dependencies]
hygiea-core = { workspace = true, features = ["app"] }
fred = { version = "10.1.0", features = ["sentinel-auth"] }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
