[package]
name = "hygiea-component-http-axum"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "HTTP (axum) component for hygiea"

[dependencies]
hygiea-core = { path = "../../hygiea-core", version = "0.1.1-alpha.1", features = ["app", "error"] }
hygiea = { path = "../../hygiea", version = "0.1.1-alpha.1", features = ["error"] }
axum = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tower-http = { workspace = true }
http = { workspace = true }
